version: '3'

services:
  $name;format="normalize"$-postgres:
    container_name: $name;format="normalize"$-postgres
    image: postgres:10.7
    ports:
      - "$dbPort$:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
